version: '3.1'
services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:8080"
    environment:
      NGINX_HOST=rch.org
      NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
  app:
    image: rch:latest
    restart: always
    ports:
      - "8000:8000"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rch
      POSTGRES_PASSWORD: rch
      POSTGRES_DB: rch
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "./data:/var/lib/postgresql/data"